# Generated by Django 3.2 on 2021-04-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando visitante'), ('EM_VISITA', 'Em visita'), ('VISITA_FINALIZADA', 'Visita finalizada')], default='AGUARDANDO', max_length=20, verbose_name='Status'),
        ),
    ]
